# Generated by Django 3.2.9 on 2021-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_url', models.URLField(verbose_name='Music URL')),
                ('posting_date', models.DateField(verbose_name='Posting Date')),
            ],
        ),
    ]
