# Generated by Django 3.2.9 on 2021-11-09 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdownmusic',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
    ]
