# Generated by Django 3.2.9 on 2021-11-09 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_countdownmusic_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdownmusic',
            name='days_left',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Days Left'),
            preserve_default=False,
        ),
    ]
