# Generated by Django 3.2.9 on 2021-11-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_alter_countdownmusic_days_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdownmusic',
            name='days_left',
        ),
    ]
